DEFAULTS: &DEFAULTS
  email: no-reply@example.com

development:
  domain: example.local
  <<: *DEFAULTS

test:
  domain: example.com
  <<: *DEFAULTS

staging:
  domain: staging.example.com
  <<: *DEFAULTS

production:
  domain: example.com
  <<: *DEFAULTS