development:
  adapter: postgresql
  encoding: unicode
  database: APP_NAME_development
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: APP_NAME_test
  pool: 5
  username: root
  password:
