source 'http://rubygems.org'

gem 'rails', '3.0.3'

gem 'choices'

gem 'haml', '~>3.0'
gem 'haml-rails', '~>0.3'
gem 'compass', '~>0.10'
gem 'jquery-rails'

gem 'meta-tags', '~>1.2', :require => 'meta_tags'
gem 'will_paginate', '~>2.3'
gem 'custom_error_message', '~>1.0.0'

gem 'autotest'
gem 'autotest-rails'

group :development, :test, :cucmber do
  gem 'sqlite3-ruby', :require => 'sqlite3'
  gem 'rspec-rails', '~>2.4'
end

group :test, :cucmber do
  # http://chrismdp.github.com/2010/11/getting-spork-working-now-on-rails-3-rspec-2-and-cucumber/
  gem 'spork', :git => "git://github.com/chrismdp/spork.git"

  gem 'rspec', '~>2.4'
  gem 'shoulda', '~>2.11'
  gem 'factory_girl', '~>1.3'
  gem 'email_spec', '~>1.1'
  gem 'faker'
  gem 'cucumber-rails', '0.3.2'
  gem "capybara", '~>0.4'
  gem "database_cleaner", '~>0.6'
  gem "launchy"
end

group :production do
  gem 'pg'
end
