source 'http://rubygems.org'

gem 'rails', '2.3.8'
gem 'erubis', '2.6.5'

gem 'compass'
gem 'formtastic'
gem 'haml'
gem 'searchlogic'
gem 'will_paginate'
gem 'RedCloth', '~> 4.2.3'

group :development do
  gem 'inaction_mailer', :require => 'inaction_mailer/force_load'
  gem 'mongrel', '1.1.5'
  gem 'mysql'
end

group :test do
  gem 'spork', '0.8.4'
  gem 'rspec', '1.3.0'
  gem 'rspec-rails', '1.3.2'
  gem 'shoulda', '2.10.2'
  gem 'factory_girl', '1.3.2'
  gem 'email_spec', '0.6.2'
  gem 'faker'
end

group :cucumber do
  gem 'cucumber-rails', '0.3.2'
  gem 'database_cleaner', '0.5.0'
  gem 'webrat', '0.7.0'
  gem 'rspec', '1.3.0'
  gem 'rspec-rails', '1.3.2'
  gem 'factory_girl', '1.3.2'
  gem 'faker'
end

group :production do
  gem 'pg'
end